// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Department", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("api.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Documentation")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Responsibles")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Sectorid")
                        .HasColumnType("int");

                    b.Property<string>("Tools")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("finished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("parentProcessId")
                        .HasColumnType("int");

                    b.Property<string>("prioprity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Sectorid");

                    b.HasIndex("parentProcessId");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("api.Models.Sector", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("departmentId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("departmentId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("api.Models.Process", b =>
                {
                    b.HasOne("api.Models.Sector", null)
                        .WithMany("processes")
                        .HasForeignKey("Sectorid");

                    b.HasOne("api.Models.Process", "parentProcess")
                        .WithMany("children")
                        .HasForeignKey("parentProcessId");

                    b.Navigation("parentProcess");
                });

            modelBuilder.Entity("api.Models.Sector", b =>
                {
                    b.HasOne("api.Models.Department", "department")
                        .WithMany("sectors")
                        .HasForeignKey("departmentId");

                    b.Navigation("department");
                });

            modelBuilder.Entity("api.Models.Department", b =>
                {
                    b.Navigation("sectors");
                });

            modelBuilder.Entity("api.Models.Process", b =>
                {
                    b.Navigation("children");
                });

            modelBuilder.Entity("api.Models.Sector", b =>
                {
                    b.Navigation("processes");
                });
#pragma warning restore 612, 618
        }
    }
}
